from playwright.sync_api import sync_playwright
from http.server import ThreadingHTTPServer, SimpleHTTPRequestHandler
from functools import partial
from threading import Thread
server=ThreadingHTTPServer(('127.0.0.1',0),partial(SimpleHTTPRequestHandler,directory='/mnt/data/plumbing_takeoff_v3'))
Thread(target=server.serve_forever,daemon=True).start()
p=f'http://127.0.0.1:{server.server_port}/index.html'
with sync_playwright() as pw:
 b=pw.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox','--allow-file-access-from-files'])
 page=b.new_page(viewport={'width':390,'height':844},accept_downloads=True)
 errs=[]
 page.on('pageerror',lambda e:errs.append(str(e)))
 page.on('dialog',lambda d:d.accept())
 page.goto('file:///mnt/data/plumbing_takeoff_v3/index.html')
 assert page.get_by_text('لا توجد قوائم بعد.').is_visible()
 page.get_by_role('button',name='＋ معاينة مشروع جديد').click()
 page.locator('#pn').fill('شقة الاختبار')
 page.locator('#pc').fill('عميل اختبار')
 page.get_by_role('button',name='حفظ ومتابعة المعاينة').click()
 page.locator('#placeNew').fill('حمام 1')
 page.get_by_role('button',name='إضافة',exact=True).click()
 page.get_by_role('button',name='＋ أضف خامة').click()
 page.locator('#in').fill('كوع PPR')
 page.locator('#is').fill('25 مم')
 page.locator('#iq').fill('8')
 page.get_by_role('button',name='إضافة الصنف').click()
 page.locator('#placeNew').fill('مطبخ')
 page.get_by_role('button',name='إضافة',exact=True).click()
 page.get_by_role('button',name='＋ أضف خامة').click()
 page.locator('#in').fill('كوع PPR')
 page.locator('#is').fill('25 مم')
 page.locator('#iq').fill('6')
 page.get_by_role('button',name='إضافة الصنف').click()
 page.get_by_role('button',name='التقرير').click()
 assert '14' in page.locator('#reportBody').inner_text()
 assert page.get_by_text('مسودة غير معتمدة.').first.is_visible()
 page.get_by_role('button',name='المعاينة').click()
 page.get_by_role('button',name='راجع البنود').click()
 page.get_by_role('button',name='✓ اعتماد الحصر الحالي').click()
 assert page.get_by_text('✓ الحصر معتمد.').is_visible()
 page.get_by_role('button',name='المعاينة').click()
 page.get_by_role('button',name='تعديل').last.click()
 page.locator('#iq').fill('7')
 page.get_by_role('button',name='حفظ التعديل').click()
 page.get_by_role('button',name='التقرير').click()
 assert '15' in page.locator('#reportBody').inner_text()
 assert page.get_by_text('مسودة غير معتمدة.').first.is_visible()
 page.reload()
 assert '15' in page.locator('#reportBody').inner_text() if page.locator('#reportBody').count() else True
 page.get_by_role('button',name='المشروعات').click()
 assert page.get_by_text('شقة الاختبار').is_visible()
 page.screenshot(path='/mnt/data/plumbing_takeoff_v3/preview.png',full_page=True)
 assert not errs,errs
 print('PASS: empty initial state, create project, locations, add/edit items, group totals 14->15, approval invalidation, persisted project, no JS errors')
 b.close()
