import 'package:flutter/material.dart';
import 'database.dart';
import 'models.dart';

void main() => runApp(const PlumbingApp());

class PlumbingApp extends StatelessWidget { const PlumbingApp({super.key}); @override Widget build(BuildContext context) => MaterialApp(debugShowCheckedModeBanner: false, title: 'حصر خامات السباكة', theme: ThemeData(colorSchemeSeed: const Color(0xff144637), useMaterial3: true), home: const Directionality(textDirection: TextDirection.rtl, child: HomePage())); }

class HomePage extends StatefulWidget { const HomePage({super.key}); @override State<HomePage> createState() => _HomePageState(); }
class _HomePageState extends State<HomePage> {
  final db = AppDatabase.instance; List<Project> projects = []; Project? selected; List<Place> places = []; List<MaterialItem> items = [];
  @override void initState() { super.initState(); refresh(); }
  Future<void> refresh() async { projects = await db.projects(); if (selected != null) { places = await db.places(selected!.id!); items = await db.materials(selected!.id!); } if (mounted) setState(() {}); }
  Future<void> newProject() async { final name = TextEditingController(); final client = TextEditingController(); final ok = await showDialog<bool>(context: context, builder: (_) => AlertDialog(title: const Text('مشروع جديد'), content: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: name, decoration: const InputDecoration(labelText: 'اسم المشروع *')), TextField(controller: client, decoration: const InputDecoration(labelText: 'اسم العميل (اختياري)'))]), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('إلغاء')), FilledButton(onPressed: () => Navigator.pop(context, name.text.trim().isNotEmpty), child: const Text('حفظ'))])); if (ok == true) { final id = await db.createProject(Project(name: name.text.trim(), client: client.text.trim())); selected = Project(id: id, name: name.text.trim(), client: client.text.trim()); await refresh(); } }
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('حصر خامات السباكة')), body: selected == null ? ListView(padding: const EdgeInsets.all(16), children: [FilledButton.icon(onPressed: newProject, icon: const Icon(Icons.add), label: const Text('مشروع جديد')), const SizedBox(height: 16), ...projects.map((p) => Card(child: ListTile(title: Text(p.name), subtitle: Text(p.client.isEmpty ? 'بدون بيانات عميل' : p.client), onTap: () async { selected = p; await refresh(); })))]): TakeoffView(project: selected!, places: places, items: items, db: db, onBack: () { setState(() => selected = null); refresh(); }, onChanged: refresh));
}

class TakeoffView extends StatefulWidget { final Project project; final List<Place> places; final List<MaterialItem> items; final AppDatabase db; final VoidCallback onBack, onChanged; const TakeoffView({super.key, required this.project, required this.places, required this.items, required this.db, required this.onBack, required this.onChanged}); @override State<TakeoffView> createState() => _TakeoffViewState(); }
class _TakeoffViewState extends State<TakeoffView> { final place = TextEditingController(); final name = TextEditingController(); final spec = TextEditingController(); final qty = TextEditingController(text: '1'); int? placeId;
  Future<void> addPlace() async { if (place.text.trim().isEmpty) return; await widget.db.addPlace(Place(projectId: widget.project.id!, name: place.text.trim())); place.clear(); widget.onChanged(); setState(() {}); }
  Future<void> addItem() async { if (placeId == null || name.text.trim().isEmpty || spec.text.trim().isEmpty) return; final q = double.tryParse(qty.text); if (q == null || q <= 0) return; await widget.db.addMaterial(MaterialItem(projectId: widget.project.id!, placeId: placeId!, name: name.text.trim(), spec: spec.text.trim(), unit: 'قطعة', quantity: q)); await widget.db.touchProject(widget.project.id!); name.clear(); spec.clear(); qty.text = '1'; widget.onChanged(); setState(() {}); }
  @override Widget build(BuildContext context) => ListView(padding: const EdgeInsets.all(16), children: [Row(children: [IconButton(onPressed: widget.onBack, icon: const Icon(Icons.arrow_back)), Expanded(child: Text(widget.project.name, style: Theme.of(context).textTheme.headlineSmall))]), Card(child: Padding(padding: const EdgeInsets.all(12), child: Row(children: [Expanded(child: TextField(controller: place, decoration: const InputDecoration(labelText: 'مكان جديد'))), const SizedBox(width: 8), FilledButton(onPressed: addPlace, child: const Text('إضافة'))]))), if (widget.places.isNotEmpty) ...[DropdownButton<int>(value: placeId ?? widget.places.first.id, isExpanded: true, items: widget.places.map((p) => DropdownMenuItem(value: p.id, child: Text(p.name))).toList(), onChanged: (v) => setState(() => placeId = v)), Card(child: Padding(padding: const EdgeInsets.all(12), child: Column(children: [TextField(controller: name, decoration: const InputDecoration(labelText: 'اسم الخامة')), TextField(controller: spec, decoration: const InputDecoration(labelText: 'المقاس والمواصفة')), TextField(controller: qty, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'الكمية')), const SizedBox(height: 8), FilledButton.icon(onPressed: addItem, icon: const Icon(Icons.add), label: const Text('إضافة الخامة'))]))), ...widget.items.map((i) => ListTile(title: Text('${i.name} · ${i.spec}'), subtitle: Text('${i.quantity} ${i.unit}')))] else const Center(child: Text('أضف مكانًا لبدء الحصر'))]); }
